language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.0.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.1.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.2.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.3.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.4.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.5.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.6.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.6.* PHPUNIT_VERSION=~3.7
    - php: hhvm
      env: SYMFONY_VERSION=2.6.* PHPUNIT_VERSION=~4.0
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*@dev PHPUNIT_VERSION=~4.0

before_script:
  - composer require --no-update "symfony/config:${SYMFONY_VERSION}"
  - composer require --no-update "phpunit/phpunit:${PHPUNIT_VERSION}"
  - composer update

notifications:
  email: matthiasnoback@gmail.com
